#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index_admin:
    path: /indexAdmin
    controller: App\Controller\FreelanceController::indexAdmin

app_visitor:
    path: /visitor
    controller: App\Controller\VisitorController::index

app_event_new:
    path: /new
    controller: App\Controller\EventController::new
    methods: ['GET', 'POST']

app_organisation_new:
    path: /add/organisation
    controller: App\Controller\OrganisationController::new
    methods: ['GET', 'POST']



contract_new:
    path: /contract_back/new
    controller: App\Controller\ContratController::new_back
    methods: ['GET', 'POST']

# Route pour afficher tous les contrats
contract_show:
    path: /contract_back/show
    controller: App\Controller\ContratController::show_back
    methods: ['GET']

# Route pour éditer un contrat existant
contract_edit:
    path: /contract_back/edit/{id}
    controller: App\Controller\ContratController::edit_back
    methods: ['GET', 'POST']

# Route pour supprimer un contrat existant
contract_delete:
    path: /contract_back/delete/{id}
    controller: App\Controller\ContratController::deleteContrat_back
    methods: ['DELETE']

#organisation_back_show:
 # path: '/organisation_back/show/{id}'
 # controller: 'App\Controller\OrganisationController::show_back_organisation'
 # methods: ['GET']

organisation_back_show:
  path: '/organisation_back/show'
  controller: 'App\Controller\OrganisationController::show_back'
  methods: ['GET']


app_organisation_back_show:
  path: '/organisation_back/{id}'
  controller: 'App\Controller\OrganisationController::show_back'
  methods: ['GET']
  requirements:
    id: \d+  # Assurez-vous que l'ID est un nombre (expression régulière)

acceuil_contrats:
  path: /explorez_contrats
  controller: App\Controller\ContratController::acceuil
  methods: [GET]

# config/routes.yaml
#app_mon_graphique:
    #path: /mongraphique
    #controller: App\Controller\ContratController::monGraphique
app_mon_graphique:
    path: '/graph'
    controller: 'App\Controller\ContratController::indexAction'

# routes.yaml

app_mon_stats:
    path: /stats
    controller: App\Controller\ContratController::contratStats
    methods: ['GET']
#[Route('/contractsbyyear', name: 'app_year')]
app_year:
    path: /contractsbyyear
    controller: App\Controller\ContratController::contractsByYear
    methods: ['GET']
#[Route('/year', name: 'app_mon_year')]

app_mon_year:
    path: /year
    controller: App\Controller\ContratController::contractsbyStats
    methods: ['GET']
   


app_mon_statts_projet:
    path: '/statsbyprojet'
    controller: 'App\Controller\ContratController::contratStatsbyproject'
contrat_stats_by_freelance:
    path: /stats-by-freelance
    controller: App\Controller\ContratController::contratStatsByFreelance












app_event_delete:
    path: '/event/{id}/delete'
    controller: 'App\Controller\EventController::delete'
    methods: ['GET','POST'] # Ensure that only POST requests are allowed

    # config/routes.yaml
app_event_show:
    path: '/event/{id}'
    controller: 'App\Controller\EventController::show'
    methods: ['GET']

app_event_edit:
    path: '/event/{id}/edit'
    controller: 'App\Controller\EventController::edit'
    methods: ['GET', 'POST']



app_logout:
    path: /logout
    controller: App\Controller\EventController::logout


components_add:
    path: /components-ADD.html
    controller: App\Controller\EventController::new

    

components_edit:
    path: /components-EDIT.html
    controller: App\Controller\EventController::edit

components_show:
    path: /components-SHOW.html
    controller: App\Controller\EventController::show

components_delete:
    path: /components-DELETE.html
    controller: App\Controller\EventController::delete







