#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index_admin:
    path: /indexAdmin
    controller: App\Controller\FreelanceController::indexAdmin

app_visitor:
    path: /visitor
    controller: App\Controller\VisitorController::index
app_event_new:
    path: /new
    controller: App\Controller\EventController::new
    methods: ['GET', 'POST']